@startmindmap

+[#OrangeRed] Writing

++[#yellow] 写作

+++[#Pink] 10个技巧

++++[#MediumSpringGreen] 写出音乐感
+++++[#LightGreen] 写作应该长短结合，像写曲子，让读者从视觉上和听觉上感觉到韵律

++++[#MediumSpringGreen] “triad”（三合音）
+++++[#LightGreen] 举例时，只举三个，因为这样读起来最有节奏感

++++[#MediumSpringGreen] CTA = call to action
+++++[#LightGreen] 你需要让读者有所收获，而告诉她们应该做什么，就是回报她们的最好方式
+++++[#LightGreen] 这是一个广告常用术语，指的告诉读者如何行动
+++++[#LightGreen] 如果我们写的是非虚构类文字，最好包含至少一个 CTA

++++[#MediumSpringGreen] 一寸相框
+++++[#LightGreen] 先写下眼前已经明确的，最想说的那个点子，不要考虑全文最后的呈现
+++++[#LightGreen] 先写下一句最想说的话，最想表达的点子，已经成型的想法

++++[#MediumSpringGreen] 填满画布
+++++[#LightGreen] 写作难，如果没有十足的气势，难免半途而废
+++++[#LightGreen] 当开始写草稿时，应该一鼓作气，先填满画布。我们不能犹豫，因为犹豫就会败北。

++++[#MediumSpringGreen] 简单和清晰
+++++[#LightGreen] ”为了更清楚地表达，我需要不断提醒自己，丝毫不要在意呈现的优雅。“

++++[#MediumSpringGreen] 不说副词
+++++[#LightGreen] 不要用副词描绘情势，用更生动的叙述来替代它

++++[#MediumSpringGreen] 先写标题

++++[#MediumSpringGreen] 删掉“我认为”、“我觉得”、“我相信”等




'coke.do 说写作 https://twitter.com/coolXiao/status/1554667451203276801


@endmindmap