@startmindmap

+[#OrangeRed] How to Speech

++[#yellow] Patrick Winston

+++[#Pink] Things Matter in Science Career
++++[#MediumSpringGreen] Speak
++++[#MediumSpringGreen] Write
++++[#MediumSpringGreen] Quality of Idea

+++[#Pink]_ Introduction
+++[#Pink]_ Rules of Engagement

+++[#Pink] How to Start
++++[#MediumSpringGreen] Joke is note recommend
++++[#MediumSpringGreen] Outline
++++[#MediumSpringGreen] Four Sample Heuristics
+++++[#LightGreen] Cycle on the subject
+++++[#LightGreen] Build a fence around idea
+++++[#LightGreen] Verbal punctuation

+++[#Pink] The Tools

++++[#MediumSpringGreen] Boards
++++[#MediumSpringGreen] Props
++++[#MediumSpringGreen] How not to use Slides
+++++[#LightGreen] Half the information was on slides
+++++[#LightGreen] Get rid of the background junk
+++++[#LightGreen] Get rid of the logos
+++++[#LightGreen] Get rid of the title
+++++[#LightGreen] Eliminate clutter

+++[#Pink] Informing

++++[#MediumSpringGreen] Promise
++++[#MediumSpringGreen] Inspire people
++++[#MediumSpringGreen] How to Think

+++[#Pink] Persuading

++++[#MediumSpringGreen] Oral Exams
++++[#MediumSpringGreen] Job Talks
++++[#MediumSpringGreen] Getting Famous

+++[#Pink] How to Stop

++++[#MediumSpringGreen] Final Slide
+++++[#LightGreen] Your Contribution
+++++[#LightGreen] The issue you realized
+++++[#LightGreen] How to solve it

++++[#MediumSpringGreen] Final Words
+++++[#LightGreen] Joke is nice
+++++[#LightGreen] Salute the audience (Thank is not recommend)
+++++[#LightGreen] Express your happiness of the meeting


'https://www.youtube.com/watch?v=Unzc731iCUY
'
'00:16 Introduction
'03:11 Rules of Engagement
'04:15 How to Start
'05:38 Four Sample Heuristics
'10:17 The Tools: Time and Place
'13:24 The Tools: Boards, Props, and Slides
'36:30 Informing: Promise, Inspiration, How to Think
'41:30 Persuading: Oral Exams, Job Talks, Getting Famous
'53:06 How to Stop: Final Slide, Final Words
'56:35 Final Words: Joke, Thank You, Examples

@endmindmap