@startmindmap

+[#OrangeRed] English

++[#yellow] Composition

+++[#Pink] 应试技巧

++++[#MediumSpringGreen] 文章结构

+++++[#LightGreen] 总
++++++[#Aquamarine] 点题，亮明观点

+++++[#LightGreen] 分
++++++[#Aquamarine] 逻辑：因果 | 递进 | 转折

+++++[#LightGreen] 总
++++++[#Aquamarine] 总结，升华一下


++++[#MediumSpringGreen] 连词短语

+++++[#LightGreen] 两个方面
++++++[#Aquamarine]_ On the one hand
++++++[#Aquamarine]_ On the other hand

+++++[#LightGreen] 三个方面
++++++[#Aquamarine]_ First and foremost
++++++[#Aquamarine]_ Additionally | Moreover
++++++[#Aquamarine]_ Last but not least

+++++[#LightGreen] 四个方面
++++++[#Aquamarine]_ To begin with
++++++[#Aquamarine]_ Besides | Similarly | Then
++++++[#Aquamarine]_ What's more
++++++[#Aquamarine]_ Finally


++++[#MediumSpringGreen] 遣词造句

+++++[#LightGreen] 遣词
++++++[#Aquamarine] big
+++++++[#LightYellow]_ enormous | massive | gigantic | immense
++++++[#Aquamarine] nice
+++++++[#LightYellow]_ pleasant | admirable | favorable
++++++[#Aquamarine] important
+++++++[#LightYellow]_ crucial | essential | significant | critical
++++++[#Aquamarine] change
+++++++[#LightYellow]_ transform
++++++[#Aquamarine] explain
+++++++[#LightYellow]_ illustrate
++++++[#Aquamarine] always
+++++++[#LightYellow]_ consistently
++++++[#Aquamarine] fast
+++++++[#LightYellow]_ rapidly
++++++[#Aquamarine] because
+++++++[#LightYellow]_ for the reason of | for the reason that
++++++[#Aquamarine] but
+++++++[#LightYellow]_ on the contrary | in spite of

+++++[#LightGreen] 高级词汇
++++++[#Aquamarine] 私人词典


+++++[#LightGreen] 造句
++++++[#Aquamarine] 倒装 + 虚拟语气
+++++++[#LightYellow]_ Had it not been for the carrot, the rabbit could have starved to death.
++++++[#Aquamarine] 倒装 + 插入语
+++++++[#LightYellow]_ Only then did the rabbit, one of my most loyal friends, devour the massive carrot.
++++++[#Aquamarine] 非谓语动词 + 强调
+++++++[#LightYellow]_ It was the very carrot that the rabbit had eaten without anyone noticing.
++++++[#Aquamarine] 非谓语动词 + 俗语
+++++++[#LightYellow]_ Famished and exhausted, the rabbit gobbled down the carrot at the drop of a hat.
++++++[#Aquamarine] 独立主格 + 俗语
+++++++[#LightYellow]_ There being no shortage of carrots, the rabbit survived without breaking a sweat.
++++++[#Aquamarine] 双重否定 + 从句 + 被动
+++++++[#LightYellow]_ The rabbit never failed to consume all the carrots that were actually reserved for me.

+++++[#LightGreen] 高级语法

++++++[#Aquamarine] 倒装
++++++[#Aquamarine] 虚拟语气
++++++[#Aquamarine] 强调
++++++[#Aquamarine] 被动

++++++[#Aquamarine] 从句
++++++[#Aquamarine] 双重否定
++++++[#Aquamarine] 独立主格
++++++[#Aquamarine] 非谓语动词


+++++[#LightGreen] 谚语
++++++[#Aquamarine]_ Every coin has two sides.
++++++[#Aquamarine]_ When the going gets tough, the tough get going.
++++++[#Aquamarine]_ No man is an island.
++++++[#Aquamarine]_ Fortune favors the bold.



'英语作文怎样快速提分? https://www.bilibili.com/video/BV1Q64y1k7zW


@endmindmap