@startmindmap

+[#OrangeRed] Vocabulary

++[#yellow] 词根

+++[#Pink] 常用

++++[#AliceBlue] able
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=ability ability]]

++++[#AliceBlue] band
+++++[#LightYellow] 弯曲
++++++[#White] [[https://cn.bing.com/dict/search?q=bend bend]]
+++++[#LightYellow] 绑定
++++++[#White] [[https://cn.bing.com/dict/search?q=bind bind]]
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=bond bond]]
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=ability bund]]

++++[#AliceBlue] bene
+++++[#LightYellow] 有益的
++++++[#White] [[https://cn.bing.com/dict/search?q=beneficial beneficial]]
+++++[#LightYellow] 善行
++++++[#White] [[https://cn.bing.com/dict/search?q=benevolent benevolent]]
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=benefaction benefaction]]
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=benediction benediction]]

++++[#AliceBlue] bio
+++++[#LightYellow] 出生
++++++[#White] [[https://cn.bing.com/dict/search?q=birth birth]]

++++[#AliceBlue] br
+++++[#LightYellow] 眉毛
++++++[#White] [[https://cn.bing.com/dict/search?q=brow brow]]
+++++[#LightYellow] 夹子
++++++[#White] [[https://cn.bing.com/dict/search?q=brace brace]]
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=brain brain]]

++++[#AliceBlue] cane
+++++[#LightYellow] 飓风
++++++[#White] [[https://cn.bing.com/dict/search?q=hurricane hurricane]]

++++[#AliceBlue] car / char
+++++[#LightYellow] 货物
++++++[#White] [[https://cn.bing.com/dict/search?q=cargo cargo]]
+++++[#LightYellow] 搬运
++++++[#White] [[https://cn.bing.com/dict/search?q=carry carry]]
+++++[#LightYellow] 购物车
++++++[#White] [[https://cn.bing.com/dict/search?q=cart cart]]
+++++[#LightYellow] 骆驼
++++++[#White] [[https://cn.bing.com/dict/search?q=camel camel]]
+++++[#LightYellow] 充满
++++++[#White] [[https://cn.bing.com/dict/search?q=charge charge]]

++++[#AliceBlue] can / chan
+++++[#LightYellow] 管道
++++++[#White] [[https://cn.bing.com/dict/search?q=cargo channel]]

++++[#AliceBlue] dent / teeth
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=dentiform dentiform]]

++++[#AliceBlue] dur / tree
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=durable durable]]
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=duration duration]]
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=perdure perdure]]
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=obdurate obdurate]]

++++[#AliceBlue] fin
+++++[#LightYellow] 鱼鳍
++++++[#White] [[https://cn.bing.com/dict/search?q=fin fin]]
+++++[#LightYellow] 决赛选手
++++++[#White] [[https://cn.bing.com/dict/search?q=finalist finalist]]
+++++[#LightYellow] 有限的
++++++[#White] [[https://cn.bing.com/dict/search?q=finite finite]]
+++++[#LightYellow] 无限的
++++++[#White] [[https://cn.bing.com/dict/search?q=infinite infinite]]
+++++[#LightYellow] 限制
++++++[#White] [[https://cn.bing.com/dict/search?q=confine confine]]
++++++[#White] [[https://cn.bing.com/dict/search?q=confined confined]]
+++++[#LightYellow] 定义
++++++[#White] [[https://cn.bing.com/dict/search?q=define define]]

++++[#AliceBlue] horn
+++++[#LightYellow] 角
++++++[#White] [[https://cn.bing.com/dict/search?q=horn horn]]
++++++[#White] [[https://cn.bing.com/dict/search?q=unicorn unicorn]]
+++++[#LightYellow] 心脏
++++++[#White] [[https://cn.bing.com/dict/search?q=heart heart]]
+++++[#LightYellow] 核心
++++++[#White] [[https://cn.bing.com/dict/search?q=core core]]
+++++[#LightYellow] 玉米
++++++[#White] [[https://cn.bing.com/dict/search?q=corn corn]]
+++++[#LightYellow] 胡萝卜
++++++[#White] [[https://cn.bing.com/dict/search?q=carrot carrot]]

++++[#AliceBlue] lun / moon
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=lunar lunar]]
++++++[#White] [[https://cn.bing.com/dict/search?q=mooncake mooncake]]

++++[#AliceBlue] nov
+++++[#LightYellow] 新的
++++++[#White] [[https://cn.bing.com/dict/search?q=novel novel]]
+++++[#LightYellow] 创新
++++++[#White] [[https://cn.bing.com/dict/search?q=innovation innovation]]
+++++[#LightYellow] 翻新
++++++[#White] [[https://cn.bing.com/dict/search?q=renovation renovation]]

++++[#AliceBlue] pot
+++++[#LightYellow] 能喝的
++++++[#White] [[https://cn.bing.com/dict/search?q=potable potable]]
+++++[#LightYellow] 能力
++++++[#White] [[https://cn.bing.com/dict/search?q=potency potency]]
+++++[#LightYellow] 有能力的
++++++[#White] [[https://cn.bing.com/dict/search?q=potent potent]]
++++++[#White] [[https://cn.bing.com/dict/search?q=potentate potentate]]
+++++[#LightYellow] 全能的
++++++[#White] [[https://cn.bing.com/dict/search?q=omnipotent omnipotent]]
++++[#AliceBlue] pois
+++++[#LightYellow] 毒药
++++++[#White] [[https://cn.bing.com/dict/search?q=poison poison]]
+++++[#LightYellow] 有毒的
++++++[#White] [[https://cn.bing.com/dict/search?q=poisonous poisonous]]
+++++[#LightYellow] 毒害者
++++++[#White] [[https://cn.bing.com/dict/search?q=poisoner poisoner]]

++++[#AliceBlue] sam / sem / sim / syn / sy / sym / syl
+++++[#LightYellow] 相似
++++++[#White] [[https://cn.bing.com/dict/search?q=similar similar]]

++++[#AliceBlue] sol / sum / sun
+++++[#LightYellow] 唯一
++++++[#White] [[https://cn.bing.com/dict/search?q=sole sole]]
+++++[#LightYellow] 孤独
++++++[#White] [[https://cn.bing.com/dict/search?q=solitude solitude]]
++++++[#White] [[https://cn.bing.com/dict/search?q=solitary solitary]]
+++++[#LightYellow] 太阳能
++++++[#White] [[https://cn.bing.com/dict/search?q=solar solar]]
+++++[#LightYellow] 暴晒
++++++[#White] [[https://cn.bing.com/dict/search?q=insolate insolate]]
++++++[#White] [[https://cn.bing.com/dict/search?q=solarise solarise]]
+++++[#LightYellow] 暴晒
++++++[#White] [[https://cn.bing.com/dict/search?q=turnsole turnsole]]

++++[#AliceBlue] st
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=stop stop]]
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=stand stand]]
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=still still]]
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=stone stone]]

++++[#AliceBlue] tri
+++++[#LightYellow] 三倍
++++++[#White] [[https://cn.bing.com/dict/search?q=triple triple]]
+++++[#LightYellow] 三个月
++++++[#White] [[https://cn.bing.com/dict/search?q=trimester trimester]]
+++++[#LightYellow] 三胞胎
++++++[#White] [[https://cn.bing.com/dict/search?q=triplet triplet]]
+++++[#LightYellow] 三角的
++++++[#White] [[https://cn.bing.com/dict/search?q=triangular triangular]]

++++[#AliceBlue] uni / one
+++++[#LightYellow] 统一
++++++[#White] [[https://cn.bing.com/dict/search?q=unify unify]]
++++++[#White] [[https://cn.bing.com/dict/search?q=unification unification]]
+++++[#LightYellow] 统一的
++++++[#White] [[https://cn.bing.com/dict/search?q=uniform uniform]]
++++++[#White] [[https://cn.bing.com/dict/search?q=uniformity uniformity]]
+++++[#LightYellow] 再联合
++++++[#White] [[https://cn.bing.com/dict/search?q=reunion reunion]]
+++++[#LightYellow] 不团结
++++++[#White] [[https://cn.bing.com/dict/search?q=disunity disunity]]

++++[#AliceBlue] vall
+++++[#LightYellow] 山谷
++++++[#White] [[https://cn.bing.com/dict/search?q=valley valley]]
+++++[#LightYellow] 村庄
++++++[#White] [[https://cn.bing.com/dict/search?q=village village]]
+++++[#LightYellow] 别墅
++++++[#White] [[https://cn.bing.com/dict/search?q=villa villa]]

++++[#AliceBlue] vent / wind
+++++[#LightYellow] 通风口
++++++[#White] [[https://cn.bing.com/dict/search?q=vent vent]]
+++++[#LightYellow] 通风
++++++[#White] [[https://cn.bing.com/dict/search?q=ventilation ventilation]]
++++++[#White] [[https://cn.bing.com/dict/search?q=ventilative ventilative]]
++++++[#White] [[https://cn.bing.com/dict/search?q=unventilated unventilated]]
+++++[#LightYellow] 冒险
++++++[#White] [[https://cn.bing.com/dict/search?q=venture venture]]
+++++[#LightYellow] 冒险家
++++++[#White] [[https://cn.bing.com/dict/search?q=adventurer adventurer]]

++++[#AliceBlue] vis / vid
+++++[#LightYellow] 可视化
++++++[#White] [[https://cn.bing.com/dict/search?q=visualize visualize]]
+++++[#LightYellow] 复习
++++++[#White] [[https://cn.bing.com/dict/search?q=revise revise]]
+++++[#LightYellow] 预见
++++++[#White] [[https://cn.bing.com/dict/search?q=previse previse]]
+++++[#LightYellow] 远见
++++++[#White] [[https://cn.bing.com/dict/search?q=providence providence]]
+++++[#LightYellow] 没远见
++++++[#White] [[https://cn.bing.com/dict/search?q=improvident improvident]]
+++++[#LightYellow] 监督
++++++[#White] [[https://cn.bing.com/dict/search?q=supervise supervise]]
+++++[#LightYellow] 明显的
++++++[#White] [[https://cn.bing.com/dict/search?q=evident evident]]
+++++[#LightYellow] 证据
++++++[#White] [[https://cn.bing.com/dict/search?q=evidence evidence]]
+++++[#LightYellow] 反感
++++++[#White] [[https://cn.bing.com/dict/search?q=invidious invidious]]
+++++[#LightYellow] 嫉妒的
++++++[#White] [[https://cn.bing.com/dict/search?q=envious envious]]

++++[#AliceBlue] vol / will
+++++[#LightYellow] 自愿的
++++++[#White] [[https://cn.bing.com/dict/search?q=voluntarily voluntarily]]
+++++[#LightYellow] 意志力
++++++[#White] [[https://cn.bing.com/dict/search?q=volition volition]]
++++++[#White] [[https://cn.bing.com/dict/search?q=volitive volitive]]
++++++[#White] [[https://cn.bing.com/dict/search?q=volitional volitional]]

+++[#Pink] 不常用


++++[#AliceBlue] ced / cess
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=ability ability]]

++++[#AliceBlue] cid / cis
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=ability ability]]

++++[#AliceBlue] clud
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=ability ability]]

++++[#AliceBlue] duc / duct
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=ability ability]]

++++[#AliceBlue] fer
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=ability ability]]

++++[#AliceBlue] ject
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=ability ability]]

++++[#AliceBlue] migr
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=ability ability]]

++++[#AliceBlue] pend / pens
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=ability ability]]

++++[#AliceBlue] pos
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=ability ability]]

++++[#AliceBlue] rupt
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=ability ability]]

++++[#AliceBlue] spect
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=ability ability]]

++++[#AliceBlue] tract
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=ability ability]]

++++[#AliceBlue] vert / vers
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=ability ability]]

++++[#AliceBlue] viv
+++++[#LightYellow] 示威
++++++[#White] [[https://cn.bing.com/dict/search?q=ability ability]]





@endmindmap