@startmindmap

+[#OrangeRed] Vocabulary

++[#yellow] 词缀

+++[#Pink] 前缀（词向）

++++[#AliceBlue] ab
+++++[#LightGreen] abnormal
+++++[#LightGreen] abuse

++++[#AliceBlue] anti
+++++[#LightGreen] antiforeign
+++++[#LightGreen] antiwar

++++[#AliceBlue] co / col / con / com
+++++[#LightGreen] communicate
+++++[#LightGreen] cooperation
+++++[#LightGreen] contribute

++++[#AliceBlue] counter
+++++[#LightGreen] counterattack
+++++[#LightGreen] countereffect
+++++[#LightGreen] countertrend

++++[#AliceBlue] de
+++++[#LightGreen] decode
+++++[#LightGreen] decolour
+++++[#LightGreen] decompose
+++++[#LightGreen] demerit
+++++[#LightGreen] depress
+++++[#LightGreen] devalue

++++[#AliceBlue] dis
+++++[#LightGreen] disappear
+++++[#LightGreen] discolor
+++++[#LightGreen] disorder
+++++[#LightGreen] distract
+++++[#LightGreen] distribute

++++[#AliceBlue] ex
+++++[#LightGreen] exclude
+++++[#LightGreen] exit
+++++[#LightGreen] export

++++[#AliceBlue] fore
+++++[#LightGreen] forehead
+++++[#LightGreen] forefather
+++++[#LightGreen] foresee

++++[#AliceBlue] in / im
+++++[#LightGreen] inbreathe
+++++[#LightGreen] imbalance
+++++[#LightGreen] incorrect
+++++[#LightGreen] incomplete
+++++[#LightGreen] indoor
+++++[#LightGreen] immortal
+++++[#LightGreen] import
+++++[#LightGreen] impossible

++++[#AliceBlue] inter
+++++[#LightGreen] international
+++++[#LightGreen] interpersonal

++++[#AliceBlue] mis
+++++[#LightGreen] misfortune
+++++[#LightGreen] misunderstand
+++++[#LightGreen] misuse

++++[#AliceBlue] out
+++++[#LightGreen] outdoor
+++++[#LightGreen] outnumber
+++++[#LightGreen] outspend

++++[#AliceBlue] over
+++++[#LightGreen] overpraise
+++++[#LightGreen] overstudy

++++[#AliceBlue] post
+++++[#LightGreen] postgraduate
+++++[#LightGreen] postpone
+++++[#LightGreen] postwar

++++[#AliceBlue] pre
+++++[#LightGreen] precondition
+++++[#LightGreen] prehistory

++++[#AliceBlue] pro
+++++[#LightGreen] progress
+++++[#LightGreen] prolong

++++[#AliceBlue] re
+++++[#LightGreen] rebirth
+++++[#LightGreen] recall
+++++[#LightGreen] reconsider
+++++[#LightGreen] regress
+++++[#LightGreen] return

++++[#AliceBlue] sub
+++++[#LightGreen] subaverage
+++++[#LightGreen] subbranch
+++++[#LightGreen] subtitle
+++++[#LightGreen] subway

++++[#AliceBlue] trans
+++++[#LightGreen] transform
+++++[#LightGreen] transplant
+++++[#LightGreen] transposition



+++[#Pink] 数字前缀

++++[#AliceBlue] hemi
+++++[#LightGreen] hemicycle
+++++[#LightGreen] hemisphere

++++[#AliceBlue] semi
+++++[#LightGreen] semiautomatic
+++++[#LightGreen] semifinal

++++[#AliceBlue] mono
+++++[#LightGreen] monodrama
+++++[#LightGreen] monotone

++++[#AliceBlue] bi
+++++[#LightGreen] bicycle
+++++[#LightGreen] bilateral

++++[#AliceBlue] di
+++++[#LightGreen] dioxide
+++++[#LightGreen] divorce

++++[#AliceBlue] tri
+++++[#LightGreen] triangle
+++++[#LightGreen] trike

++++[#AliceBlue] poly
+++++[#LightGreen] monopoly
+++++[#LightGreen] polytechnic

++++[#AliceBlue] multi
+++++[#LightGreen] multi-media
+++++[#LightGreen] multi-purpose


+++[#Pink] 后缀（词性）

++++[#AliceBlue] able
+++++[#LightGreen] adaptable
+++++[#LightGreen] movable
+++++[#LightGreen] useable

++++[#AliceBlue] al
+++++[#LightGreen] natural
+++++[#LightGreen] regional
+++++[#LightGreen] personal

+++++[#LightGreen] arrival
+++++[#LightGreen] criminal
+++++[#LightGreen] refusal
+++++[#LightGreen] survival

++++[#AliceBlue] ate
+++++[#LightGreen] generate

+++++[#LightGreen] advocate
+++++[#LightGreen] candidate
+++++[#LightGreen] graduate

++++[#AliceBlue] 44
+++++[#LightGreen] 54



@endmindmap