@startmindmap

+[#OrangeRed] 不及物动词

++[#yellow] Verb intransitive

+++[#Pink] 搭配

++++[#MediumSpringGreen] 常用

+++++[#LightGreen] participate in sth | 参与
+++++[#LightGreen] be aware of sth | 意识到
+++++[#LightGreen] focus / concentrate on sth | 专注于
+++++[#LightGreen] consist of | 由...组成

++++[#MediumSpringGreen] 基础

+++++[#LightGreen] rely / depend on sth | 依赖于
+++++[#LightGreen] agree with sb | 同意
+++++[#LightGreen] apply for sth | 申请
+++++[#LightGreen] pay attention to sth | 注意
+++++[#LightGreen] be interested in | 感兴趣
+++++[#LightGreen] wait for sb / sth | 等待
+++++[#LightGreen] arrive at / in (at 小地方 如 school, in 城市国家)

++++[#MediumSpringGreen] 其他

+++++[#LightGreen] adjust / adapt to sth | 适应
+++++[#LightGreen] complain about sth | 抱怨
+++++[#LightGreen] be related to sth | 有关联
+++++[#LightGreen] be addicted to sth | 上瘾



+++++[#LightGreen] 5
++++++[#Aquamarine] 6
+++++++[#GhostWhite] 7
++++++++[#LightYellow] 8

++++++[#Aquamarine]_ 6
+++++++[#GhostWhite]_ 7
++++++++[#LightYellow]_ 8

++++[#AliceBlue] 4
+++++[#GhostWhite] 5
++++++[#LightBlue] 6




@endmindmap