@startmindmap

+[#OrangeRed] Vocabulary

++[#yellow] preposition

+++[#Orange] 介词

++++[#Pink] 转折

+++++[#DeepSkyBlue] 退

++++++[#LightYellow] 即使、尽管
+++++++[#White] [[https://cn.bing.com/dict/search?q=despite despite]]


+++[#Pink] 名词后的介词搭配

++++[#MediumSpringGreen] to
+++++[#LightGreen] the answer to the question
+++++[#LightGreen] the key to success
+++++[#LightGreen] the solution to this problem
+++++[#LightGreen] the entrance to the museum
+++++[#LightGreen] the attitude to(ward) marriage
+++++[#LightGreen] the access to the Internet
+++++[#LightGreen] the alternative to fossil fuels
+++++[#LightGreen] the approach to environmental protection
+++++[#LightGreen] the reply to one's message

++++[#MediumSpringGreen] of
+++++[#LightGreen] the price of coat
+++++[#LightGreen] the chance of success
+++++[#LightGreen] members of the team


++++[#MediumSpringGreen] 介词搭配小结

+++++[#LightGreen] 名词后的介词经常用 of，但有例外
+++++[#LightGreen] of 具有明显的附属性
+++++[#LightGreen] to 具有映射性
+++++[#LightGreen] for 具有一个具象服务另一个具象的意思











@endmindmap