@startmindmap

+[#OrangeRed] Vocabulary

++[#yellow] adverb

+++[#Orange] 副词

++++[#Pink] 转折

+++++[#DeepSkyBlue] 而

++++++[#LightYellow] 然而
+++++++[#White] [[https://cn.bing.com/dict/search?q=nevertheless nevertheless]]


++++++[#LightYellow] 然而
+++++++[#White] [[https://cn.bing.com/dict/search?q=however however]]


++++++[#LightYellow] 然而
+++++++[#White] [[https://cn.bing.com/dict/search?q=regardless regardless]]



++++[#Pink] 补充

+++++[#DeepSkyBlue] 且

++++++[#LightYellow] 另外
+++++++[#White] [[https://cn.bing.com/dict/search?q=furthermore furthermore]]





++++[#Pink] 因果

+++++[#DeepSkyBlue] 果

++++++[#LightYellow] 所以、因此
+++++++[#White] [[https://cn.bing.com/dict/search?q=hence hence]]






@endmindmap