@startmindmap

+[#OrangeRed] Vocabulary

++[#yellow] 常见

+++[#Orange] 动词


++++[#Pink] 中性

+++++[#DeepSkyBlue] 示

++++++[#LightYellow] 示威
+++++++[#White] [[https://cn.bing.com/dict/search?q=demonstrate demonstrate]]
++++++++[#White] [[https://cn.bing.com/dict/search?q=demonstrator demonstrator]]
+++++++++[#LightYellow] 示威者

++++++[#LightYellow] 暗示
+++++++[#White] [[https://cn.bing.com/dict/search?q=hint hint]]

+++++[#DeepSkyBlue] 大

++++++[#LightYellow] 膨胀
+++++++[#White] [[https://cn.bing.com/dict/search?q=swell swell]]


+++++[#DeepSkyBlue] 多

++++++[#LightYellow] 涌入
+++++++[#White] [[https://cn.bing.com/dict/search?q=influx influx]]


+++++[#DeepSkyBlue] 卷

++++++[#LightYellow] 争夺
+++++++[#White] [[https://cn.bing.com/dict/search?q=scramble scramble]]


+++++[#DeepSkyBlue] 近

++++++[#LightYellow] 逼近
+++++++[#White] [[https://cn.bing.com/dict/search?q=loom loom]]


+++++[#DeepSkyBlue] 像

++++++[#LightGreen] 相似
+++++++[#White] [[https://cn.bing.com/dict/search?q=resemble resemble]]






++++[#Pink] 褒义

+++++[#DeepSkyBlue] 揭

++++++[#LightYellow] 揭示
+++++++[#White] [[https://cn.bing.com/dict/search?q=reveal reveal]]

++++++[#LightGreen] 揭露
+++++++[#White] [[https://cn.bing.com/dict/search?q=unveil unveil]]

+++++[#DeepSkyBlue] 呼

++++++[#LightYellow] 呼吁
+++++++[#White] [[https://cn.bing.com/dict/search?q=appeal appeal]]
++++++++[#White]_ appeal to

++++++[#LightYellow] 申明
+++++++[#White] [[https://cn.bing.com/dict/search?q=affirm affirm]]
++++++++[#White] [[https://cn.bing.com/dict/search?q=reaffirm reaffirm]]
+++++++++[#LightYellow] 重申

++++++[#LightGreen] 敦促
+++++++[#White] [[https://cn.bing.com/dict/search?q=urge urge]]

+++++[#DeepSkyBlue] 究

++++++[#LightYellow] 探究
+++++++[#White] [[https://cn.bing.com/dict/search?q=probe probe]]


+++++[#DeepSkyBlue] 提

++++++[#LightGreen] 提到
+++++++[#White] [[https://cn.bing.com/dict/search?q=mention mention]]





++++[#Pink] 负面

+++++[#DeepSkyBlue] 撞

++++++[#LightYellow] 撞击
+++++++[#White] [[https://cn.bing.com/dict/search?q=ram ram]]

+++++[#DeepSkyBlue] 偷

++++++[#LightYellow] 偷窃
+++++++[#White] [[https://cn.bing.com/dict/search?q=swipe swipe]]

+++++[#DeepSkyBlue] 争

++++++[#LightYellow] 纠纷
+++++++[#White] [[https://cn.bing.com/dict/search?q=dispute dispute]]


+++++[#DeepSkyBlue] 杀

++++++[#LightYellow] 杀害
+++++++[#White] [[https://cn.bing.com/dict/search?q=slay slay]]
++++++++[#GhostWhite] slain（过去分词）


+++++[#DeepSkyBlue] 伤

++++++[#LightYellow] 使断肢
+++++++[#White] [[https://cn.bing.com/dict/search?q=mutilate mutilate]]

+++++[#DeepSkyBlue] 毁

++++++[#LightYellow] 毁灭
+++++++[#White] [[https://cn.bing.com/dict/search?q=wreck wreck]]
++++++++[#White] [[https://cn.bing.com/dict/search?q=shipwreck shipwreck]]
+++++++++[#LightYellow] 沉船

++++++[#LightYellow] 破坏
+++++++[#White] [[https://cn.bing.com/dict/search?q=sabotage sabotage]]

++++++[#LightYellow] 塌陷
+++++++[#White] [[https://cn.bing.com/dict/search?q=collapse collapse]]


+++++[#DeepSkyBlue] 悲

++++++[#LightYellow] 悼念
+++++++[#White] [[https://cn.bing.com/dict/search?q=mourn mourn]]








+++[#Orange] -

++++[#Pink] 0

+++++[#DeepSkyBlue] 1

++++++[#LightYellow] 2
+++++++[#White] [[https://cn.bing.com/dict/search?q= ]]



@endmindmap