@startmindmap

+[#OrangeRed] Vocabulary

++[#yellow] 常见

+++[#Orange] 名词

++++[#Pink] 中性

+++++[#DeepSkyBlue] 情

++++++[#LightGreen] 情绪
+++++++[#White] [[https://cn.bing.com/dict/search?q=sentiment sentiment]]

+++++[#DeepSkyBlue] 房

++++++[#LightYellow] 公寓
+++++++[#White] [[https://cn.bing.com/dict/search?q=condo condo]]

++++++[#LightGreen] 按揭、抵押
+++++++[#White] [[https://cn.bing.com/dict/search?q=mortgage mortgage]]

+++++[#DeepSkyBlue] 车

++++++[#LightGreen] 卡车
+++++++[#White] [[https://cn.bing.com/dict/search?q=truck truck]]

++++++[#LightGreen] 车辆
+++++++[#White] [[https://cn.bing.com/dict/search?q=vehicle vehicle]]


+++++[#DeepSkyBlue] 州

++++++[#LightGreen] 爱荷华州
+++++++[#White] [[https://cn.bing.com/dict/search?q=Iowa Iowa]]



+++++[#DeepSkyBlue] 数

++++++[#LightGreen] 十二个
+++++++[#White] [[https://cn.bing.com/dict/search?q=dozen dozen]]

+++++[#DeepSkyBlue] 军

++++++[#LightYellow] 部队
+++++++[#White] [[https://cn.bing.com/dict/search?q=troop troop]]


++++++[#LightYellow] 预备役军人
+++++++[#White] [[https://cn.bing.com/dict/search?q=reservist reservist]]







++++[#Pink] 褒义

+++++[#DeepSkyBlue] 法

++++++[#LightYellow] 起诉人
+++++++[#White] [[https://cn.bing.com/dict/search?q=prosecutor prosecutor]]

++++++[#LightYellow] 陪审团
+++++++[#White] [[https://cn.bing.com/dict/search?q=jury jury]]

++++++[#LightYellow] 审判
+++++++[#White] [[https://cn.bing.com/dict/search?q=trial trial]]


+++++[#DeepSkyBlue] 医

++++++[#LightYellow] 诊所
+++++++[#White] [[https://cn.bing.com/dict/search?q=clinic clinic]]


+++++[#DeepSkyBlue] 政

++++++[#LightYellow] 提名
+++++++[#White] [[https://cn.bing.com/dict/search?q=nomination nomination]]







++++[#Pink] 负面

+++++[#DeepSkyBlue] 危

++++++[#LightGreen] 危机
+++++++[#White] [[https://cn.bing.com/dict/search?q=crisis crisis]]
++++++++[#GhostWhite] crises（复数）

++++++[#LightGreen] 经济衰退
+++++++[#White] [[https://cn.bing.com/dict/search?q=recession recession]]


+++++[#DeepSkyBlue] 亡

++++++[#LightYellow] 伤亡人数
+++++++[#White] [[https://cn.bing.com/dict/search?q=toll toll]]
++++++++[#GhostWhite] crises（复数）


+++++[#DeepSkyBlue] 地震

++++++[#LightYellow] 余震
+++++++[#White] [[https://cn.bing.com/dict/search?q=aftershock aftershock]]







+++[#Orange] -

++++[#Pink] 0

+++++[#DeepSkyBlue] 1

++++++[#LightYellow] 2
+++++++[#White] [[https://cn.bing.com/dict/search?q= ]]



@endmindmap