@startmindmap

+[#OrangeRed] Vocabulary

++[#yellow] noun

+++[#Orange] 名词

++++[#Pink] 中性

+++++[#DeepSkyBlue] 论

++++++[#LightGreen] 假说
+++++++[#White] [[https://cn.bing.com/dict/search?q=hypothesis hypothesis]]
++++++++[#Aquamarine]_ 害怕会社死

++++++[#LightGreen] 理论
+++++++[#White] [[https://cn.bing.com/dict/search?q=theory theory]]

++++++[#LightGreen] 概念
+++++++[#White] [[https://cn.bing.com/dict/search?q=concept concept]]

++++++[#LightGreen] 上下文
+++++++[#White] [[https://cn.bing.com/dict/search?q=context context]]

++++++[#LightGreen] 示例、案例
+++++++[#White] [[https://cn.bing.com/dict/search?q=instance instance]]

++++++[#LightGreen] 信息；事实
+++++++[#White] [[https://cn.bing.com/dict/search?q=data data]]

++++++[#LightGreen] 演讲；教学
+++++++[#White] [[https://cn.bing.com/dict/search?q=instance instance]]


+++++[#DeepSkyBlue] 工

++++++[#LightGreen] 工程、项目；预测
+++++++[#White] [[https://cn.bing.com/dict/search?q=project project]]



+++++[#DeepSkyBlue] 机

++++++[#LightGreen] 运行；功能
+++++++[#White] [[https://cn.bing.com/dict/search?q=function function]]

++++++[#LightGreen] 方法、方式
+++++++[#White] [[https://cn.bing.com/dict/search?q=method method]]

++++++[#LightGreen] 特性、属性；包含某特性
+++++++[#White] [[https://cn.bing.com/dict/search?q=feature feature]]

++++++[#LightGreen] 主题，问题
+++++++[#White] [[https://cn.bing.com/dict/search?q=issue issue]]



+++++[#DeepSkyBlue] 说



+++++[#DeepSkyBlue] 情

++++++[#LightGreen] 情绪
+++++++[#White] [[https://cn.bing.com/dict/search?q=sentiment sentiment]]

+++++[#DeepSkyBlue] 房

++++++[#LightYellow] 公寓
+++++++[#White] [[https://cn.bing.com/dict/search?q=condo condo]]

++++++[#LightGreen] 按揭、抵押
+++++++[#White] [[https://cn.bing.com/dict/search?q=mortgage mortgage]]

+++++[#DeepSkyBlue] 车

++++++[#LightGreen] 卡车
+++++++[#White] [[https://cn.bing.com/dict/search?q=truck truck]]

++++++[#LightGreen] 车辆
+++++++[#White] [[https://cn.bing.com/dict/search?q=vehicle vehicle]]


+++++[#DeepSkyBlue] 州

++++++[#LightGreen] 爱荷华州
+++++++[#White] [[https://cn.bing.com/dict/search?q=Iowa Iowa]]


+++++[#DeepSkyBlue] 洲

++++++[#LightGreen] 大洲
+++++++[#White] [[https://cn.bing.com/dict/search?q=continent continent]]


+++++[#DeepSkyBlue] 数

++++++[#LightGreen] 十二个
+++++++[#White] [[https://cn.bing.com/dict/search?q=dozen dozen]]


+++++[#DeepSkyBlue] 军

++++++[#LightYellow] 部队
+++++++[#White] [[https://cn.bing.com/dict/search?q=troop troop]]


++++++[#LightYellow] 预备役军人
+++++++[#White] [[https://cn.bing.com/dict/search?q=reservist reservist]]


+++++[#DeepSkyBlue] 教

++++++[#LightYellow] 宗教
+++++++[#White] [[https://cn.bing.com/dict/search?q=religion religion]]




++++[#Pink] 褒义

+++++[#DeepSkyBlue] 法

++++++[#LightYellow] 起诉人
+++++++[#White] [[https://cn.bing.com/dict/search?q=prosecutor prosecutor]]

++++++[#LightYellow] 陪审团
+++++++[#White] [[https://cn.bing.com/dict/search?q=jury jury]]

++++++[#LightYellow] 审判
+++++++[#White] [[https://cn.bing.com/dict/search?q=trial trial]]


+++++[#DeepSkyBlue] 医

++++++[#LightYellow] 诊所
+++++++[#White] [[https://cn.bing.com/dict/search?q=clinic clinic]]


+++++[#DeepSkyBlue] 政

++++++[#LightYellow] 提名
+++++++[#White] [[https://cn.bing.com/dict/search?q=nomination nomination]]







++++[#Pink] 负面

+++++[#DeepSkyBlue] 危

++++++[#LightGreen] 危机
+++++++[#White] [[https://cn.bing.com/dict/search?q=crisis crisis]]
++++++++[#GhostWhite] crises（复数）

++++++[#LightGreen] 经济衰退
+++++++[#White] [[https://cn.bing.com/dict/search?q=recession recession]]


+++++[#DeepSkyBlue] 亡

++++++[#LightYellow] 伤亡人数
+++++++[#White] [[https://cn.bing.com/dict/search?q=toll toll]]
++++++++[#GhostWhite] crises（复数）


+++++[#DeepSkyBlue] 地震

++++++[#LightYellow] 余震
+++++++[#White] [[https://cn.bing.com/dict/search?q=aftershock aftershock]]







+++[#Orange] -

++++[#Pink] 0

+++++[#DeepSkyBlue] 1

++++++[#LightYellow] 2
+++++++[#White] [[https://cn.bing.com/dict/search?q= ]]



@endmindmap