@startmindmap

+[#OrangeRed] Vocabulary

++[#yellow] adjective

+++[#Orange] 形容词


++++[#Pink] 褒义

+++++[#DeepSkyBlue] 足

++++++[#LightYellow] 足够的
+++++++[#White] [[https://cn.bing.com/dict/search?q=adequate adequate]]
++++++++[#Aquamarine]_ 额滴夸她

++++++[#LightYellow] 充足的
+++++++[#White] [[https://cn.bing.com/dict/search?q=sufficient sufficient]]


+++++[#DeepSkyBlue] 持

++++++[#LightYellow] 持续的
+++++++[#White] [[https://cn.bing.com/dict/search?q=constant constant]]


+++++[#DeepSkyBlue] 重

++++++[#LightYellow] 重要的、明显的
+++++++[#White] [[https://cn.bing.com/dict/search?q=significant significant]]


+++++[#DeepSkyBlue] 精

++++++[#LightYellow] 精确的、准确的
+++++++[#White] [[https://cn.bing.com/dict/search?q=accurate accurate]]


+++++[#DeepSkyBlue] 能

++++++[#LightYellow] 有能力的
+++++++[#White] [[https://cn.bing.com/dict/search?q=capable capable]]





++++[#Pink] 中性


+++++[#DeepSkyBlue] 简

++++++[#LightYellow] 简短的
+++++++[#White] [[https://cn.bing.com/dict/search?q=brief brief]]

++++++[#LightYellow] 总体；一般来说、大部分
+++++++[#White] [[https://cn.bing.com/dict/search?q=overall overall]]


+++++[#DeepSkyBlue] 基

++++++[#LightYellow] 基本的、核心的，极其重要的
+++++++[#White] [[https://cn.bing.com/dict/search?q=fundamental fundamental]]
++++++++[#Aquamarine]_ The fundamental beliefs of most religions are peaceful.




+++++[#DeepSkyBlue] 肃

++++++[#LightYellow] 庄严的
+++++++[#White] [[https://cn.bing.com/dict/search?q=solemn solemn]]


+++++[#DeepSkyBlue] 最

++++++[#LightYellow] 空前的
+++++++[#White] [[https://cn.bing.com/dict/search?q=unprecedented unprecedented]]



+++++[#DeepSkyBlue] 永

++++++[#LightYellow] 永久地
+++++++[#White] [[https://cn.bing.com/dict/search?q=permanently permanently]]






++++[#Pink] 负面


+++++[#DeepSkyBlue] 厌

++++++[#LightYellow] 可憎的
+++++++[#White] [[https://cn.bing.com/dict/search?q=odious odious]]
++++++++[#White] [[https://cn.bing.com/dict/search?q=odd odd]]
+++++++++[#LightYellow] 怪异的









@endmindmap