@startmindmap

+[#OrangeRed] Vocabulary

++[#yellow] 常见

+++[#Orange] 形容词


++++[#Pink] 褒义


++++[#Pink] 中性

+++++[#DeepSkyBlue] 肃

++++++[#LightYellow] 庄严的
+++++++[#White] [[https://cn.bing.com/dict/search?q=solemn solemn]]


+++++[#DeepSkyBlue] 最

++++++[#LightYellow] 空前的
+++++++[#White] [[https://cn.bing.com/dict/search?q=unprecedented unprecedented]]



+++++[#DeepSkyBlue] 永

++++++[#LightYellow] 永久地
+++++++[#White] [[https://cn.bing.com/dict/search?q=permanently permanently]]







++++[#Pink] 负面


+++++[#DeepSkyBlue] 厌

++++++[#LightYellow] 可憎的
+++++++[#White] [[https://cn.bing.com/dict/search?q=odious odious]]
++++++++[#White] [[https://cn.bing.com/dict/search?q=odd odd]]
+++++++++[#LightYellow] 怪异的





+++[#Orange] -

++++[#Pink] 0

+++++[#DeepSkyBlue] 1

++++++[#LightYellow] 2
+++++++[#White] [[https://cn.bing.com/dict/search?q= ]]



@endmindmap