@startmindmap

+[#OrangeRed] English

++[#yellow] idiom 惯用语

+++[#Pink] elephant
++++[#MediumSpringGreen] An elephant never forgets
+++++[#LightGreen] 记忆力好
++++[#MediumSpringGreen] The elephant in the room
+++++[#LightGreen] 大家都知道，但是却避免谈论的话题
++++[#MediumSpringGreen] White elephant
+++++[#LightGreen] 昂贵且无用的，未达预期的东西
++++[#MediumSpringGreen] Seeing pink elephants
+++++[#LightGreen] 喝醉酒看见幻象



'https://www.bilibili.com/video/BV1dv4y1M7Gd


@endmindmap