@startmindmap

+[#OrangeRed] Vocabulary

++[#yellow] conjunction

+++[#Orange] 连词

++++[#Pink] 转折

+++++[#DeepSkyBlue] 退

++++++[#LightYellow] 虽然；然而
+++++++[#White] [[https://cn.bing.com/dict/search?q=whereas whereas]]
++++++++[#Aquamarine]_ Lemons are very sour whereas most fruits are sweet.












@endmindmap