@startmindmap

+[#OrangeRed] IELTS

++[#yellow] Topic

+++[#Pink] Daily

++++[#MediumSpringGreen] Clothing
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Food
+++++[#LightGreen] Cooking
++++++[#Aquamarine]_ It's very hard to get the right volume of meal.
++++++[#Aquamarine]_ 6
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Home Appliances
+++++[#LightGreen] Furniture
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Transport
+++++[#LightGreen] Metro
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#AliceBlue] Money
+++++[#LightGreen] Shopping
+++++[#LightGreen] Supermarket
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8


+++[#Pink] Emotion

++++[#MediumSpringGreen] Party
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Festivals
+++++[#LightGreen] Programmers' Day.
++++++[#Aquamarine]_ work overtime | fashion | retailer
+++++[#LightGreen] Double Eleventh Day | Single's Day
++++++[#Aquamarine]_ shopaholic | parcel | retailer
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Media
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Friendship
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Family
+++++[#LightGreen] Hometown
++++++[#Aquamarine]_ Hubei is Too hot in summer and too cold in winter.
++++++[#Aquamarine]_ Too difficult to find nice job in my county.
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#AliceBlue] Childhood
+++++[#LightGreen] Toy
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] People
+++++[#LightGreen] Grand Mother
+++++[#LightGreen] Elon Mask
+++++[#LightGreen] John Stanford
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8


+++[#Pink] Hobby

++++[#MediumSpringGreen] Travel
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Sports
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Music
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Game
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Fashion
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Reading
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Writing
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#AliceBlue] Likes
+++++[#LightGreen] Website
+++++[#LightGreen] Film
+++++[#LightGreen] TV Channel
+++++[#LightGreen] Meal
+++++[#LightGreen] Prize
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#AliceBlue] Dislikes
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8


+++[#Pink] Nature

++++[#MediumSpringGreen] Nature
+++++[#LightGreen] Season
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Environment
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Animals
+++++[#LightGreen] Wild Animal
+++++[#LightGreen] Pets
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8


+++[#Pink] Work

++++[#MediumSpringGreen] Work
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Co-operation
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Skill
+++++[#LightGreen] Coding
+++++[#LightGreen] Painting
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#AliceBlue] Plan
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#AliceBlue] Effort
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#AliceBlue] Decision
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#AliceBlue] Solutions
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8


+++[#Pink] Utility

++++[#AliceBlue] Education
+++++[#LightGreen] Subject
+++++[#LightGreen] Lesson
+++++[#LightGreen] Library
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#AliceBlue] Culture
+++++[#LightGreen] Foreign Culture
+++++[#LightGreen] Advertising
++++++[#Aquamarine]_ 6
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Science
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Technology
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Health
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Fitness
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8


+++[#Pink] Society

++++[#MediumSpringGreen] City
+++++[#LightGreen] Shenzhen
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Traffic
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Buildings
+++++[#LightGreen] Library
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#MediumSpringGreen] Development
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#AliceBlue] Crime
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#AliceBlue] Law
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#AliceBlue] Justice
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#AliceBlue] Government
+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8



++[#yellow] 2

+++[#Pink] 3

++++[#MediumSpringGreen] 4
+++++[#LightGreen] 5
++++++[#Aquamarine] 6
+++++++[#LightYellow] 7
++++++++[#GhostWhite] 8

+++++[#LightGreen] 5
++++++[#Aquamarine]_ 6
+++++++[#LightYellow]_ 7
++++++++[#GhostWhite]_ 8

++++[#AliceBlue] 4
+++++[#GhostWhite] 5
++++++[#LightBlue] 6




@endmindmap