@startmindmap

+[#OrangeRed] Oral

++[#yellow] Part2

+++[#Pink] Category(6)

++++[#MediumSpringGreen] 地点类

+++++[#LightGreen] 素材
++++++[#Aquamarine] 咖啡厅
++++++[#Aquamarine] 原因
+++++++[#GhostWhite]_ 有故事的地方
+++++++[#GhostWhite]_ 免费蛋糕
+++++++[#GhostWhite]_ 熊孩子
+++++++[#GhostWhite]_ 艰难的决定
+++++++[#GhostWhite]_ 初见某人的经历

+++++[#LightGreen] 考题
++++++[#Aquamarine] 安静的地方
++++++[#Aquamarine] 读书写作的地方
++++++[#Aquamarine] 新发现的去处

+++++[#LightGreen] 要点
++++++[#Aquamarine] 位置
++++++[#Aquamarine] 怎么找到的
++++++[#Aquamarine] 墙上有什么
++++++[#Aquamarine] 安静
++++++[#Aquamarine] 服务水平
++++++[#Aquamarine] 熊孩子

++++[#MediumSpringGreen] 事件类

+++++[#LightGreen] 素材
++++++[#Aquamarine] trip: 旅行
++++++[#Aquamarine] 原因
+++++++[#GhostWhite]_ 万能
+++++++[#GhostWhite]_ 故事多
++++++[#Aquamarine] 参考
+++++++[#GhostWhite]_ 古镇
+++++++[#GhostWhite]_ 名山

+++++[#LightGreen] 考题
++++++[#Aquamarine] 度假之地
++++++[#Aquamarine] 汽车旅行
++++++[#Aquamarine] 徒步经历
++++++[#Aquamarine] 乡村一隅
++++++[#Aquamarine] 污染城市

+++++[#LightGreen] 要点
++++++[#Aquamarine] 景区
++++++[#Aquamarine] 建筑特色
++++++[#Aquamarine] 一处具体景点
++++++[#Aquamarine] 与朋友做了什么

++++[#MediumSpringGreen] 人物类

+++++[#LightGreen] 素材
++++++[#Aquamarine] 歌手
++++++[#Aquamarine] 原因
+++++++[#GhostWhite]_ 歌手好讲，运动员难讲
++++++[#Aquamarine] 参考
+++++++[#GhostWhite]_ Taylor Swift
+++++++[#GhostWhite]_ Katy Perry
+++++++[#GhostWhite]_ Ed Sheeran
+++++++[#GhostWhite]_ Lady Gaga

+++++[#LightGreen] 考题
++++++[#Aquamarine] 社交媒体常刷到的人
++++++[#Aquamarine] 有创造力的人
++++++[#Aquamarine] 一句歌词
++++++[#Aquamarine] 壮志未酬

+++++[#LightGreen] 要点
++++++[#Aquamarine] 欧美创作型歌手
++++++[#Aquamarine] 近年有啥突破
++++++[#Aquamarine] 最爱的一句歌词

++++[#MediumSpringGreen] 物品类

+++++[#LightGreen] 素材
++++++[#Aquamarine] 科技产品 App
++++++[#Aquamarine] 原因
+++++++[#GhostWhite]_ 天天在用
++++++[#Aquamarine] 参考
+++++++[#GhostWhite]_ Alipay
+++++++[#GhostWhite]_ Didi
+++++++[#GhostWhite]_ HelloBike
+++++++[#GhostWhite]_ TikTok
+++++++[#GhostWhite]_ Eleme

+++++[#LightGreen] 考题
++++++[#Aquamarine] 改变世界的发明
++++++[#Aquamarine] 生活中离不开的东西
++++++[#Aquamarine] 帮助别人

+++++[#LightGreen] 要点
++++++[#Aquamarine] 简介
++++++[#Aquamarine] 两个功能
++++++[#Aquamarine] 交集
++++++[#Aquamarine] 背后的老板

++++[#MediumSpringGreen] 运动类

+++++[#LightGreen] 素材
++++++[#Aquamarine] 水上运动
++++++[#Aquamarine] 原因
+++++++[#GhostWhite]_ 篮球和游泳，不适用水上运动的话题
++++++[#Aquamarine] 参考
+++++++[#GhostWhite]_ snorkeling: 浮潜
+++++++[#GhostWhite]_ kayaking: 皮划艇

+++++[#LightGreen] 考题
++++++[#Aquamarine] 运动
++++++[#Aquamarine] 水上运动

+++++[#LightGreen] 要点
++++++[#Aquamarine] 第一次接触
++++++[#Aquamarine] 操作要点

++++[#MediumSpringGreen] 抽象概念类

+++++[#LightGreen] 素材
++++++[#Aquamarine] 不用太多外貌描述，人物的核心是好的品格
++++++[#Aquamarine] 至少要选两个品质

+++++[#LightGreen] 考题
++++++[#Aquamarine] 钦佩的家人
++++++[#Aquamarine] 尊重的老人
++++++[#Aquamarine] 帮助你的人
++++++[#Aquamarine] 有趣的谈话

+++++[#LightGreen] 参考品格
++++++[#Aquamarine] Patient: 有耐心
++++++[#Aquamarine] English: 英语好
++++++[#Aquamarine] Time management: 时间管理
++++++[#Aquamarine] Leadership: 领导力


++[#yellow] 2

+++[#Pink] 3

++++[#MediumSpringGreen] 4
+++++[#LightGreen] 5
++++++[#Aquamarine] 6
+++++++[#GhostWhite] 7
++++++++[#LightYellow] 8

++++++[#Aquamarine]_ 6
+++++++[#GhostWhite]_ 7
++++++++[#LightYellow]_ 8

++++[#AliceBlue] 4
+++++[#GhostWhite] 5
++++++[#LightBlue] 6




@endmindmap