@startmindmap

+[#OrangeRed] Grammar

++[#yellow] 词类

+++[#Pink] Pronoun | 代词

++++[#MediumSpringGreen] 分类
+++++[#LightGreen] 人称代词
++++++[#Aquamarine] I | we | you | you | he | they | she | they | it | they
++++++[#Aquamarine] me | us | you | you | him | them | her | them | it | them

+++++[#LightGreen] 物主代词
++++++[#Aquamarine] my | our | your | your | his | their | her | their | its | their
++++++[#Aquamarine] mine | ours | yours | yours | his | theirs | hers | theirs | its | their

+++++[#LightGreen] 反身代词
++++++[#Aquamarine] myself | yourself | himself | herself | itself
++++++[#Aquamarine] ourselves | yourselves | themselves | themselves | themselves

+++++[#LightGreen] 指示代词
++++++[#Aquamarine] this | that
++++++[#Aquamarine] these | those

+++++[#LightGreen] 强调代词
++++++[#Aquamarine] 句中做状语
++++++[#Aquamarine] The rabbit will do it himself.

+++++[#LightGreen] 相互代词
++++++[#Aquamarine] each other | one another

+++++[#LightGreen] 不定代词
++++++[#Aquamarine] many | a few | a little | some | each | either | both | (the) other | one
++++++[#Aquamarine] much | few | little | any | every | neither | all | another | it
++++++[#Aquamarine] 复合不定代词：every- | some- | any- | no-

+++++[#LightGreen] 疑问代词
++++++[#Aquamarine] who | whom | what | which | whose

+++++[#LightGreen] 连接代词
++++++[#Aquamarine] who | whom | whose | what | which | whoever | whomever | whatever | whichever

+++++[#LightGreen] 关系代词
++++++[#Aquamarine] who | whom | whose | which | that | as


++++[#MediumSpringGreen] 格
+++++[#LightGreen] 主格
+++++[#LightGreen] 宾格
+++++[#LightGreen] 所有格




'英语语法: 代词 https://www.bilibili.com/video/BV1vP4y157Mp



@endmindmap