@startmindmap

+[#OrangeRed] Grammar

++[#yellow] 词类

+++[#Pink] Interjection | 叹词

++++[#MediumSpringGreen] 表达情感

+++++[#LightGreen] 积极
++++++[#Aquamarine] 打招呼
+++++++[#GhostWhite]_ hello; hi; hey; yo; hiya
++++++[#Aquamarine] 高兴
+++++++[#GhostWhite]_ ah! yeah! yay! hooray! aha! alas! Thank god!
++++++[#Aquamarine] 鼓励
+++++++[#GhostWhite]_ yes! congratulations! congrats! bravo! come on; attaboy
++++++[#Aquamarine] 赞同
+++++++[#GhostWhite]_ yes; yep; ok; okay; indeed; cool; bingo; great; excellent; brilliant; fantastic
++++++[#Aquamarine] 感动
+++++++[#GhostWhite]_ aww

+++++[#LightGreen] 中性
++++++[#Aquamarine] 犹豫
+++++++[#GhostWhite]_ hmm, er, uh, um, erm, well, oh well
++++++[#Aquamarine] 确认
+++++++[#GhostWhite]_ please? yeah? eh? right?
++++++[#Aquamarine] 反对
+++++++[#GhostWhite]_ no; nope; no way; nah
++++++[#Aquamarine] 使注意
+++++++[#GhostWhite]_ psst
++++++[#Aquamarine] 使安静
+++++++[#GhostWhite]_ sssh
++++++[#Aquamarine] 惊讶
+++++++[#GhostWhite]_ oh; ooh; oh my god! Jesus! gee; oh my! huh?! wow; gosh; oh deer; dear me; oh my goodness; oh boy


+++++[#LightGreen] 消极
++++++[#Aquamarine] 后悔
+++++++[#GhostWhite]_ oops
++++++[#Aquamarine] 伤心
+++++++[#GhostWhite]_ no; oh no
++++++[#Aquamarine] 头疼
+++++++[#GhostWhite]_ ow; ouch
++++++[#Aquamarine] 厌恶
+++++++[#GhostWhite]_ eww; ugh
++++++[#Aquamarine] 不耐烦
+++++++[#GhostWhite]_ oh man; duh; darn; damn; blah blah blah; yadda yadda yadda
++++++[#Aquamarine] 愤怒
+++++++[#GhostWhite]_ for god's sake; Jesus; Jesus Christ; shit; fuck; what the fuck; what the hell



'你知道这些英语叹词吗 https://www.bilibili.com/video/BV1kS4y1r7gq



@endmindmap