@startmindmap

+[#OrangeRed] Vocabulary

++[#yellow] 词汇

+++[#Orange] 提高

++++[#Pink] 生词

+++++[#LightGreen] 常用

++++++[#Aquamarine] 生词

+++++++[#White] imply | [] |  |
+++++++[#White] conduct | [] |  |
+++++++[#White] regulate | [] |  | 调节、控制
+++++++[#White] sustain | [] |  | 维持
+++++++[#White] equivalent | [] |  |
+++++++[#White] philosophy | [] |  |
+++++++[#White] distribute | [] |  |
+++++++[#White] layer | [] |  |
+++++++[#White] prior | [] |  | 原
+++++++[#White] correspond | [] |  | 相符

+++++++[#White] balloon | [] |  |
+++++++[#White] moist | [] |  |
+++++++[#White] pyjamas | [] |  |
+++++++[#White] cure | [] |  |
+++++++[#White] lure | [] |  |
+++++++[#White] beige | [] |  |
+++++++[#White] bathe | [] |  |
+++++++[#White] chuck | [] |  |
+++++++[#White] chop | [] |  |
+++++++[#White] pitch | [] |  |
+++++++[#White] loll | [] |  |
+++++++[#White] dew | [] |  |
+++++++[#White] laundry | [] |  |
+++++++[#White] colleague | [] |  |
+++++++[#White] college | [] |  |
+++++++[#White] salmon | [] |  |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |



+++++[#LightGreen] 专门

++++++[#Aquamarine] 名词

+++++++[#White] impose | [ɪmˈpoʊz] | v. 推行；迫使；强制实行
+++++++[#White] impede | [ɪmˈpid] | v. 阻碍；阻止 | impede sth
+++++++[#White] deter | [] | v. 阻止；威慑；使不敢
+++++++[#White] compel | [] | v. 强迫；迫使
+++++++[#White] advocate | [] | v. 提倡；拥护；支持
+++++++[#White] inability | [] | n. 不能；无力；无能
+++++++[#White] resent | [rɪˈzent] | v. 愤恨；感到气愤；愤愤不平 |
+++++++[#White] obscure | [əbˈskjʊr] | v. 使模糊；使隐晦；使费解 | adj. 无名的；鲜为人知的；难以理解的 | obscure sth
+++++++[#White] linger | [] | v. 流连；徘徊；逗留；磨蹭
+++++++[#White] hazard | [] | n. 危害；危险
+++++++[#White] regime | [] | n. 政体；组织方法；管理体制
+++++++[#White] hierarchy | [] | n. 层次体系；等级制度（尤指社会或组织）；统治集团
+++++++[#White] preemptive | [priˈemptɪv] | adj.〔政〕先发制人的；优先权的 | n.先买权的
+++++++[#White] controversy | [] | n. 争议
+++++++[#White] controversial | [] | adj. 引起争论的；有争议的
+++++++[#White] downfall | [] | n. 垮台；衰落；衰败
+++++++[#White] drain | [] | n. 消耗；下水道；排水管；耗竭 | v. 排空；流出；（使）流光；放干
+++++++[#White] provoke | [] | v. 引发；激起；挑衅
+++++++[#White] roar | [] | v. 吼叫；咆哮；叫喊
+++++++[#White] defiant | [] | [dɪˈfaɪənt | adj.反抗的；公然违抗的；挑衅的 |
+++++++[#White] convey | [] | v. 表达；输送；运送；传送
+++++++[#White] concede | [] | v. 让步；允许；承认（某事属实、合乎逻辑等）；承认（比赛、选举等失败）
+++++++[#White] entirely | [] | adv. 完全地；全部地；完整地
+++++++[#White] tribe | [] | n. 部落；族；（尤指同一职业的）一伙（人）
+++++++[#White] revolutionary | [ˌrevəˈluʃ(ə)nˌeri] | adj. 革命的；革命性的；大变革的；巨变的 | n.（支持）改革者；革命支持者
+++++++[#White] colonel | [] | n. 上校
+++++++[#White] landmine | [] | n. 地雷
+++++++[#White] landline | [] | n. 座机
+++++++[#White] anchor | [] | n. 锚；给以安全感的人（或物）；精神支柱；顶梁柱 | v. 抛锚；下锚；使固定；扣牢
+++++++[#White] foe | [foʊ] | n.敌人；仇敌 |
+++++++[#White] leash | [liʃ] | n. 链条 | v. 用皮带系住
+++++++[#White] distort | [dɪˈstɔrt] | v.扭曲；歪曲；使变形；使失真 | distort sth
+++++++[#White] twist | [twɪst] | v.捻；扭转；曲折；扭动 | n.捻；拧；扭动；搓
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |



+++++[#LightGreen] 工作

++++++[#Aquamarine] 名词

+++++++[#White] consent 同意；允许；准许
+++++++[#White] foster 培养；促进；鼓励
+++++++[#White] persist 保持；维持；顽强地坚持
+++++++[#White] readily 乐意地；快捷地；轻而易举地
+++++++[#White] coherent 合乎逻辑的；有条理的；有表达能力的
+++++++[#White] reconcile 调和；使配合；使和解
+++++++[#White] conducive | [kənˈdusɪv] | adj. 有益于…的 | conducive to sth | conducive to doing sth
+++++++[#White] culminate （以某种结果）告终；（在某一点）结束
+++++++[#White] complicated 复杂的；难懂的
+++++++[#White] convoluted 复杂的；盘绕的
+++++++[#White] defective 有缺点的；有缺陷的；有毛病的
+++++++[#White] drawback 缺点；不利条件
+++++++[#White] overwhelm 压倒，淹没，击败
+++++++[#White] impartial | [ɪmˈpɑrʃ(ə)l] | adj.公正的；不偏不倚的；中立的 |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |

++++++[#Aquamarine] 开发

+++++++[#White] concurrency | [kən'kʌrənsɪ] | n.〔计〕并发性 |
+++++++[#White] coincide | [ˌkoʊɪnˈsaɪd] | v.相符；重叠；同时发生；相同 | sth coincide with sth
+++++++[#White] overlap | [ˈoʊvərˌlæp] | v.交叠；使部分重叠；（时间上）部分重叠；（范围方面）部分重叠 | n.（范围方面的）重叠部分；重叠量；交接时期
+++++++[#White] lap | [læp] | n.搭接；膝；怀；膝头 | v.搭接；研磨；舔；重叠
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |



+++++[#LightGreen] 学术

++++++[#Aquamarine] 形容词

+++++++[#White] perpetual motion machine 永动机
+++++++[#White] momentum 动量；势头；动力
+++++++[#White] specimen 样本
+++++++[#White] rigid 坚韧的，不屈的
+++++++[#White] prestigious 有声望的
+++++++[#White] ambiguous 模棱两可的；含混不清的；多义的
+++++++[#White] tentative 试探；尝试；实验
+++++++[#White] inclination | n. 倾向；倾斜度；趋向；意愿
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |




+++++[#LightGreen] 爱好

++++++[#Aquamarine] 名词

+++++++[#White] tint | [] | n. 色调；浅色；淡色彩
+++++++[#White] shine | [ʃaɪn] | v. 发光；反光；照耀；把…照向 |  adj. 明亮的；灿烂的；出色的 | n. 光亮；光泽
+++++++[#White] shimmer | [ˈʃɪmər] | v. 发出微弱的闪光；闪烁 | n. 闪烁的光
+++++++[#White] decorate | [ˈdekəˌreɪt] | v. 装饰；装点；装潢；点缀 |
+++++++[#White] decoration | [ˌdekəˈreɪʃ(ə)n]  | n. 装潢；装饰品；勋章；奖章 |
+++++++[#White] ornamental | [ˌɔrnəˈment(ə)l] | n. 观赏植物；装饰物 | adj. 装饰性的；点缀的
+++++++[#White] stunning | [] | adj. 绝妙的；给人以深刻印象的；极有魅力的；令人惊奇万分的 | v. stun 的现在分词
+++++++[#White] stun | [] | n. 震惊；晕眩 | v. 使昏迷；（尤指）打昏；使震惊（或惊愕、目瞪口呆）
+++++++[#White] durable | [ˈdʊrəb(ə)l] | adj. 耐用的；耐久的；长期的；长久的 | n. 耐久品
+++++++[#White] endure | [ɪnˈdʊr] | v.忍受；忍耐；持续；持久 |
+++++++[#White] era | [] | n. 新时期；纪元；年代
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |


+++++[#LightGreen] 人

++++++[#Aquamarine] 爱

+++++++[#White] endeavor | n. 努力 | v. 努力
+++++++[#White] persevere | [ˌpɜsəˈvɪr] | v. 坚持；孜孜以求
+++++++[#White] persistent | [pərˈsɪstənt] | adj.执着的；不屈不挠的；坚持不懈的；连绵的
+++++++[#White] conform | [kənˈfɔrm] | v. 遵守；相一致；顺从；相符合 | conform to sth | conform with sth
+++++++[#White] cleanliness | [ˈklenlinəs] | n. 清洁；干净；爱干净的习惯 |
+++++++[#White] guideline | [ˈɡaɪdˈlaɪn] ] | 官方指南 |
+++++++[#White] courteous | [ˈkɜrtiəs] | adj.有礼貌的；客气的；（尤指）恭敬的 |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |



++++++[#Aquamarine] 恨
+++++++[#White] eccentric | n.怪人；偏心圆；【机】偏心器；【天】离心圈 | adj.古怪的；异乎寻常的
+++++++[#White] indifference | [] | n. 漠不关心；冷淡；不感兴趣；无动于衷 | indifference to sb/sth |
+++++++[#White] extravagant | [ɪkˈstrævəɡənt] | adj. 奢侈的；挥霍的；铺张浪费的；过于昂贵的 |
+++++++[#White] ceremony | [ˈserəˌmoʊni] | n. 仪式；典礼；礼仪；礼节 |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |


++++++[#Aquamarine] 医药

+++++++[#White] cough | [kɑf] | n.咳嗽；咳嗽声；咳嗽病 | v.咳嗽；（从喉咙或肺中）咳出；突然发出刺耳的声音
+++++++[#White] sneeze | [] | v.打喷嚏 | n. 喷嚏；喷嚏声
+++++++[#White] pneumonia | [nuˈmoʊniə] | n. 肺炎 |
+++++++[#White] medication | [] | n. 药物 |
+++++++[#White] aspirin | [ˈæsprɪn] | n. 阿司匹林（镇痛解热消炎药） |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |


++++++[#Aquamarine] 生物

+++++++[#White] mouse | mice(复数) | n.【计】鼠标 (器)；姑娘；【动】(比 rat 小的) 小鼠；胆小的人 | v.【计】使用鼠标；(猫和枭) 捉耗子；来回窥探；搜捕
+++++++[#White] extinct | [ɪkˈstɪŋkt] | adj.(动植物,语言)灭绝的；(习俗,工作等)消失的；指死火山 |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |



++++++[#Aquamarine] 自然

+++++++[#White] tranquility | [ˈtræŋkwɪlətɪ] | n.宁静 |
+++++++[#White] rapture | [ˈræptʃər] | n.狂喜；兴高采烈；欢天喜地 |
+++++++[#White] watcher | [] | n.注视者；看守人；值班员；守夜人 |
+++++++[#White] axis | [ˈæksɪs] | n.坐标轴；轴（旋转物体假想的中心线）；对称中心线（将物体平分为二） |
+++++++[#White] aurora | [ɔː'rɔːrə] | n.极光；曙光；【罗神】曙光女神；【女名】女子名 |
+++++++[#White] Centaurus | [sɛnˈtɔrəs] | n.【天】半人马(星)座 |
+++++++[#White] entropy | [ˈentrəpi] | n.无序状态测量法；熵（物资系统的不能用来做功的能量的度量） |
+++++++[#White] automatic | [ˌɔtəˈmætɪk] | adj.自动的；无意识的；不假思索的；必然的 | n.自动步枪；自动变速汽车；自动换挡汽车
+++++++[#White] echo | [ˈekoʊ] | n.回声；回音；回响；反响 | v.回响；重复；回荡；模仿
+++++++[#White] edge | [edʒ] | n.边缘；边沿；刀刃；利刃 | v.渐渐移动；给…加边；略为增加（或减少）
+++++++[#White] creature | [ˈkritʃər] | n.生物；东西；创造物；〈美〉牛马 |
+++++++[#White] crystal | [ˈkrɪst(ə)l] | n.水晶；结晶体；【化】晶体；水晶玻璃(制品) | adj.晶莹的；如水晶般的；清楚的；显而易见的
+++++++[#White] choir | [ˈkwaɪr] | n.(教堂,学校的)唱诗班；唱诗席 |
+++++++[#White] chant | [tʃænt] | v.吟唱；歌颂；赞扬；卖唱 | n.【宗教】颂歌；单调的歌；吟诵语调；呆板无味
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |



+++++[#LightGreen] 生活

++++++[#Aquamarine] 灾难

+++++++[#White] flood 洪水；水灾；大量（的人或事物）
+++++++[#White] grab | [ɡræb] | n. 猛然的抓取；突然的抢夺；抓取（或截获、采集）的图像；抓斗 | v. 抓住；攫取；（试图）抓住；抓住（机会）
+++++++[#White] chase | [tʃeɪs] | v. 追逐；追求；追赶；追捕 | n. 追逐；追赶；追捕；努力获得
+++++++[#White] vaccine | [ˈvækˌsin] | adj. 牛痘的；预防疫苗的；种痘的 |
+++++++[#White] widespread | [ˈwaɪdˌspred] | adj. 分布广的；普遍的；大量的；广泛应用的 |
+++++++[#White] preventable | [prɪˈventəb(ə)l] | adj. 可阻止的；可预防的 |
+++++++[#White] suffer | [ˈsʌfər] | v.遭受；蒙受；受难；变差 |
+++++++[#White] shipwrecked | [ˈʃɪpˌrekt] | n.沉船；海难；船舶失事；失事的船 | v.遭遇海难；船只失事
+++++++[#White] rescue | [ˈreskju] | n.救援；抢救；营救；获救 | v.抢救；营救；援救
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |



++++++[#Aquamarine] 日常

+++++++[#White] beak
+++++++[#White] peck
+++++++[#White] sip
+++++++[#White] dip
+++++++[#White] dab
+++++++[#White] slender 苗条的；纤细的；窄的
+++++++[#White] thigh 大腿；股；（食用的鸡等的）大腿
+++++++[#White] palm 手掌
+++++++[#White] scrap 小块（纸、布匹等）；一丁点；残羹剩饭
+++++++[#White]  | [] |  |
+++++++[#White] cling | [klɪŋ] | v. 附着；依附；抓紧；紧握 | cling to sb | clung(过)
+++++++[#White] warp | [wɔrp] | n. 经纱 | v. 弯曲；使（行为等）不合情理；使乖戾 | warp sth
+++++++[#White] bend | [bend] | v. 弯曲；（使）倾斜；（使四肢等）弯曲；把… 弄弯（或折起） | n. 弯道；（潜水员过快浮出水面造成的）减压病
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |


++++++[#Aquamarine] 家乡

+++++++[#White] mend | [mend] | v. 修补；修理；愈合；缝补 | n. 修理；改进；痊愈；修理部份
+++++++[#White] lobster | [ˈlɑbstər] | n. 大虾；【鱼】龙虾；龙虾肉；傻子 |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |
+++++++[#White]  | [] |  |




+++++[#LightGreen] 对立

++++++[#Aquamarine] 名词

+++++++[#White] demolish | [dɪˈmɑlɪʃ] | v. 拆毁；破坏；驳倒（观点或理论）；轻易而彻底地打败
+++++++[#White] establish | [] | v. 建立；确立；设立；确定

+++++++[#White] vast | [væst] | adj. 辽阔的；巨大的；庞大的；大量的
+++++++[#White] abundant | [əˈbʌndənt] | adj. 大量的；丰盛的；充裕的

+++++++[#White] adequate | [] | adj. 足够的；合格的；合乎需要的
+++++++[#White] sufficient | [] | adj. 足够的；充足的 | n. 足够 (的量)

+++++++[#White] scarce | [] | 缺乏的；不足的；稀少的。勉强；刚；几乎不
+++++++[#White] devoid | [dɪˈvɔɪd] | adj. 完全没有；缺乏 | be devoid of humor




@endmindmap